---

- name: Get all state
  set_fact:
    all_state: "{{lookup('asb_state', get_all=True) }}"

- debug: msg="the value of foo.txt is {{all_state.some-key}}"

- name: test the new asb_state lookup plugin
  set_fact:
    some_test_var: "{{lookup('asb_state', 'some-key') }}"

- debug: msg="the value of foo.txt is {{some_test_var}}"


- name: Testing changed status should report ok
  asb_set_state:
    fields:
      some-other-key : "some_val"


- asb_encode_binding:
    fields:
      CLIENT_ID: "{{ CLIENT_ID }}"
  when: encode_asb_binding
